title: "Cadshaper"
description: "A design and drafting company for fabrication"
baseurl: "" # Leave empty for GitHub Pages
url: "https://cadshaper.github.io/" # Replace with your GitHub Pages URL
paginate: 5

markdown: kramdown

collections:
  projects:
    output: true

